service: ejercicio-15

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  getCake:
    handler: handler.handler
    events:
      - http:
          path: /get-cake
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
